export type Article={id:string;title:string;type:'Customer'|'Internal';category:string;summary:string;updated:string;read:string;content:string[];tags:string[]};
export const articles:Article[]=[
{id:'KB-101',title:'Troubleshoot webhook delivery failures',type:'Customer',category:'Integrations',summary:'A structured workflow for isolating event creation, delivery and receiver failures.',updated:'Sep 04, 2026',read:'6 min',tags:['webhooks','api','delivery'],content:['Confirm whether the expected event was created before investigating delivery. An event that never existed and an event that failed delivery are different problems.','Review the delivery attempt and receiver response. A 4xx usually points toward the receiving endpoint or its expectations; timeouts and 5xx responses may require retry and receiver-availability investigation.','If multiple independent customers show missing delivery attempts in the same period, preserve timestamps and request or event IDs and contact Support with the evidence.']},
{id:'KB-102',title:'Resolve sign-in loops in your browser',type:'Customer',category:'Authentication',summary:'Safe browser checks for repeated redirects after successful authentication.',updated:'Aug 28, 2026',read:'4 min',tags:['login','browser','session'],content:['First confirm whether the issue reproduces in another supported browser or a private session. This helps separate account-wide behavior from local browser state.','Clear Arcway site data rather than all browser history when possible, then retry authentication.','If the loop persists across clean sessions and devices, capture the approximate time and browser version before contacting Support.']},
{id:'KB-103',title:'Understand API rate limits and 429 responses',type:'Customer',category:'API',summary:'How to interpret quota headers, Retry-After and safer retry behavior.',updated:'Aug 19, 2026',read:'5 min',tags:['api','429','rate limit'],content:['HTTP 429 indicates that the client has exceeded an applicable request limit in this fictional API model.','Inspect rate-limit response headers and honor Retry-After when provided. Immediate repeated retries can prolong the problem.','Reduce unnecessary bursts and implement appropriate retry/backoff behavior in the integration.']},
{id:'INT-201',title:'Runbook — multi-customer API degradation',type:'Internal',category:'Incident Response',summary:'Internal triage, evidence collection and escalation path for correlated API failures.',updated:'Sep 06, 2026',read:'8 min',tags:['incident','api','sev2'],content:['Validate scope across independent accounts, regions and endpoints. Link related support tickets to a shared investigation rather than troubleshooting each as an isolated customer configuration issue.','Capture safe request IDs, timestamps, status codes, affected operations and whether previously healthy requests changed. Check service telemetry or known incident signals.','When evidence supports shared platform degradation, assign an incident owner, classify severity, establish an update cadence and escalate a concise evidence package to Engineering.']},
{id:'INT-202',title:'Customer communication during incidents',type:'Internal',category:'Communication',summary:'Principles and templates for accurate, useful incident updates.',updated:'Sep 02, 2026',read:'7 min',tags:['communication','incident','status'],content:['Acknowledge confirmed impact without speculating about an unverified root cause. State what customers are experiencing, what the team is doing and when the next update is expected.','Updates should change when there is meaningful new information, but the promised cadence should still be respected even if investigation continues.','Resolution communication should distinguish mitigation from validated recovery and include any customer action required.']},
{id:'INT-203',title:'Engineering escalation evidence checklist',type:'Internal',category:'Escalation',summary:'Minimum context that makes a technical escalation actionable.',updated:'Aug 30, 2026',read:'5 min',tags:['engineering','escalation','evidence'],content:['Include impact, expected versus actual behavior, safe identifiers, timestamps, reproduction scope and troubleshooting already completed.','State the hypothesis as a hypothesis, not a confirmed cause. Make the question for Engineering explicit.','Never include customer secrets, passwords or full API credentials in an escalation package.']}
];
export const timeline=[['09:18','Detected','Support links three reports of delayed file processing across independent accounts.'],['09:27','Triaged','Shared behavior reproduced; authentication and upload acceptance remain healthy.'],['09:34','SEV-2 declared','Processing queue degradation confirmed. Incident INC-117 opened.'],['09:42','Investigating','Engineering identifies elevated queue age after worker deployment.'],['10:03','Identified','Concurrency regression isolated in processing workers.'],['10:14','Mitigating','Deployment rolled back; queue begins draining.'],['10:31','Monitoring','Processing latency returns toward baseline.'],['10:48','Resolved','Recovery validated and incident closed.']];
export const services=[['API','Operational'],['Authentication','Operational'],['File uploads','Operational'],['Processing workers','Operational'],['Webhooks','Operational'],['Dashboard','Operational']];
export const severities=[{sev:'SEV-1',name:'Critical',example:'Widespread outage or severe data/security impact',response:'Immediate incident command',update:'15 min'},{sev:'SEV-2',name:'Major',example:'Material degradation affecting multiple customers or a critical workflow',response:'Rapid cross-functional response',update:'30 min'},{sev:'SEV-3',name:'Moderate',example:'Limited degradation with workaround or constrained scope',response:'Prioritized investigation',update:'As material changes occur'},{sev:'SEV-4',name:'Minor',example:'Low-impact defect, isolated issue or informational problem',response:'Standard support/product workflow',update:'Ticket cadence'}];
